### ISSUE TITLE
How to create Ambari cluster

### ISSUE THREAD

**Issue by pmint93** [sequenceiq/docker-ambari#132]
I followed instruction, i'm able to reach the Ambari UI and try to create cluster by `CLUSTER INSTALL WIZARD`, but what is the SSH private key to use in `Install Options` section ?

Or should I have to use `amb-shell` to create the cluster instead of Web UI ? Then where is the `amb-shell` instruction to create a complete cluster.

Sorry that i'm new in this kind of things, and i'm looking for a simple solution to experience hadoop ecosystem. Many thanks !

**Comment by grozeille** [comment]
Using `amb-shell` or the Web UI, it uses the same mechanism.

This project creates multiple docker images with a running ambari agent that connect to the ambari server. So you should not use SSH to install the agent, since they are already installed.
Use the 'Perform manual registration on hosts and do not use SSH' option and specify the name of the ambari docker agents (name registered in consul.io)

**Comment by pmint93** [comment]
Since I post this question, I didn't know about how it work and just follow instruction. Now, after few week to try with HDP, i understand how it work and deployed my cluster by myself.

Thanks @grozeille for your answer. Now I can close this issue 👍
